set_project("cgpui")
set_version("0.1.0")
set_languages("c++23")

add_rules("mode.debug", "mode.release")

local public_includedirs = "include"

if is_plat("windows") then
    add_requires("vulkansdk")
end

if is_plat("linux") then
    add_requires("wayland")
    add_requires("libxkbcommon", {configs = {x11 = false, wayland = false, tools = false}})
end

target("cgpui_core")
    set_kind("static")
    add_files("src/core/*.cpp")
    add_includedirs(public_includedirs, {public = true})

target("cgpui_platform")
    set_kind("static")
    add_files("src/platform/*.cpp")
    remove_files("src/platform/platform_unimplemented.cpp")
    add_deps("cgpui_core")
    add_includedirs(public_includedirs, {public = true})

target("cgpui_platform_fallback")
    set_kind("static")
    add_files("src/platform/platform_unimplemented.cpp")
    add_deps("cgpui_core", "cgpui_platform")
    add_includedirs(public_includedirs, {public = true})

if is_plat("windows") then
    target("cgpui_platform_win32")
        set_kind("static")
        add_files("src/platform/win32/*.cpp")
        add_deps("cgpui_core", "cgpui_platform")
        add_includedirs(public_includedirs, {public = true})
        add_syslinks("user32", "gdi32", "shell32")

    target("win32_input_event_test")
        set_kind("binary")
        add_files("tests/platform/win32_input_event_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_win32")
        add_includedirs(public_includedirs)
        add_syslinks("user32")
        add_tests("default")

    target("win32_dpi_scale_test")
        set_kind("binary")
        add_files("tests/platform/win32_dpi_scale_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_win32")
        add_includedirs(public_includedirs)
        add_syslinks("user32")
        add_tests("default")

    target("win32_focus_event_test")
        set_kind("binary")
        add_files("tests/platform/win32_focus_event_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_win32")
        add_includedirs(public_includedirs)
        add_syslinks("user32")
        add_tests("default")

    target("win32_text_input_test")
        set_kind("binary")
        add_files("tests/platform/win32_text_input_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_win32")
        add_includedirs(public_includedirs)
        add_syslinks("user32")
        add_tests("default")
end

if is_plat("linux") then
    target("cgpui_platform_linux_wayland")
        set_kind("static")
        add_files("src/platform/linux/*.cpp")
        add_deps("cgpui_core", "cgpui_platform")
        add_packages("wayland", "libxkbcommon")
        add_includedirs(public_includedirs, {public = true})

    target("wayland_compositor_close_test")
        set_kind("binary")
        add_files("tests/platform/wayland_compositor_close_test.cpp")
        add_files("tests/platform/wayland_test_compositor.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_linux_wayland")
        add_packages("wayland")
        add_syslinks("wayland-server")
        add_includedirs(public_includedirs)
        add_includedirs("tests/platform")
        add_tests("default")

    target("wayland_compositor_resize_test")
        set_kind("binary")
        add_files("tests/platform/wayland_compositor_resize_test.cpp")
        add_files("tests/platform/wayland_test_compositor.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_linux_wayland")
        add_packages("wayland")
        add_syslinks("wayland-server")
        add_includedirs(public_includedirs)
        add_includedirs("tests/platform")
        add_tests("default")

    target("wayland_pointer_button_test")
        set_kind("binary")
        add_files("tests/platform/wayland_pointer_button_test.cpp")
        add_files("tests/platform/wayland_test_compositor.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_linux_wayland")
        add_packages("wayland")
        add_syslinks("wayland-server")
        add_includedirs(public_includedirs)
        add_includedirs("tests/platform")
        add_tests("default")

    target("wayland_pointer_scroll_test")
        set_kind("binary")
        add_files("tests/platform/wayland_pointer_scroll_test.cpp")
        add_files("tests/platform/wayland_test_compositor.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_linux_wayland")
        add_packages("wayland")
        add_syslinks("wayland-server")
        add_includedirs(public_includedirs)
        add_includedirs("tests/platform")
        add_tests("default")

    target("wayland_keyboard_test")
        set_kind("binary")
        add_files("tests/platform/wayland_keyboard_test.cpp")
        add_files("tests/platform/wayland_test_compositor.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_linux_wayland")
        add_packages("wayland")
        add_syslinks("wayland-server")
        add_includedirs(public_includedirs)
        add_includedirs("tests/platform")
        add_tests("default")

    target("wayland_vulkan_surface_test")
        set_kind("binary")
        add_files("tests/renderer/wayland_vulkan_surface_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_linux_wayland", "cgpui_renderer", "cgpui_renderer_vulkan")
        add_packages("wayland")
        add_syslinks("vulkan")
        add_includedirs(public_includedirs)
        add_tests("default")
end

if is_plat("macosx") then
    target("cgpui_platform_macos")
        set_kind("static")
        add_files("src/platform/macos/*.mm")
        add_deps("cgpui_core", "cgpui_platform")
        add_frameworks("AppKit", "QuartzCore")
        add_includedirs(public_includedirs, {public = true})
end

target("cgpui_renderer")
    set_kind("static")
    add_files("src/renderer/*.cpp")
    remove_files("src/renderer/renderer_unimplemented.cpp")
    add_deps("cgpui_core")
    add_includedirs(public_includedirs, {public = true})

target("cgpui_renderer_fallback")
    set_kind("static")
    add_files("src/renderer/renderer_unimplemented.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer")
    add_includedirs(public_includedirs, {public = true})

if is_plat("windows", "linux") then
    target("cgpui_renderer_vulkan")
        set_kind("static")
        add_files("src/renderer/vulkan/*.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer")
        if is_plat("windows") then
            add_packages("vulkansdk")
        elseif is_plat("linux") then
            add_syslinks("vulkan")
        end
        add_includedirs(public_includedirs, {public = true})
end

if is_plat("macosx") then
    target("cgpui_renderer_metal")
        set_kind("static")
        add_files("src/renderer/metal/*.mm")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer")
        add_frameworks("Metal", "QuartzCore")
        add_includedirs(public_includedirs, {public = true})
end

target("core_header_cleanliness")
    set_kind("binary")
    add_files("tests/header_cleanliness/core_header_cleanliness.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer")
    add_includedirs(public_includedirs)
    add_tests("default")

target("entity_store_test")
    set_kind("binary")
    add_files("tests/core/entity_store_test.cpp")
    add_deps("cgpui_core")
    add_includedirs(public_includedirs)
    add_tests("default")

target("cgpui_ui")
    set_kind("static")
    add_files("src/ui/*.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer")
    add_includedirs(public_includedirs, {public = true})

target("ui_header_cleanliness")
    set_kind("binary")
    add_files("tests/header_cleanliness/ui_header_cleanliness.cpp")
    add_deps("cgpui_core", "cgpui_renderer", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("render_view_test")
    set_kind("binary")
    add_files("tests/ui/render_view_test.cpp")
    add_deps("cgpui_core", "cgpui_renderer", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("element_test")
    set_kind("binary")
    add_files("tests/ui/element_test.cpp")
    add_deps("cgpui_core", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("layout_test")
    set_kind("binary")
    add_files("tests/ui/layout_test.cpp")
    add_deps("cgpui_core", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("style_test")
    set_kind("binary")
    add_files("tests/ui/style_test.cpp")
    add_deps("cgpui_core", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("text_model_test")
    set_kind("binary")
    add_files("tests/ui/text_model_test.cpp")
    add_deps("cgpui_core", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("scroll_test")
    set_kind("binary")
    add_files("tests/ui/scroll_test.cpp")
    add_deps("cgpui_core", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("window_runtime_test")
    set_kind("binary")
    add_files("tests/ui/window_runtime_test.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("hello_window_lifetime_test")
    set_kind("binary")
    add_files("tests/architecture/hello_window_lifetime_test.cpp")
    add_tests("default")

target("wayland_window_source_test")
    set_kind("binary")
    add_files("tests/architecture/wayland_window_source_test.cpp")
    add_tests("default")

target("win32_window_source_test")
    set_kind("binary")
    add_files("tests/architecture/win32_window_source_test.cpp")
    add_tests("default")

if is_plat("windows") then
    target("vulkan_resize_test")
        set_kind("binary")
        add_files("tests/renderer/vulkan_resize_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer", "cgpui_renderer_vulkan")
        add_packages("vulkansdk")
        add_includedirs(public_includedirs)
        add_syslinks("user32")
        add_tests("default")

    target("vulkan_surface_validation_test")
        set_kind("binary")
        add_files("tests/renderer/vulkan_surface_validation_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer", "cgpui_renderer_vulkan")
        add_packages("vulkansdk")
        add_includedirs(public_includedirs)
        add_tests("default")

    target("win32_vulkan_surface_test")
        set_kind("binary")
        add_files("tests/renderer/win32_vulkan_surface_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_win32", "cgpui_renderer", "cgpui_renderer_vulkan")
        add_packages("vulkansdk")
        add_includedirs(public_includedirs)
        add_syslinks("user32", "gdi32")
        add_tests("default")

    target("vulkan_frame_lifetime_test")
        set_kind("binary")
        add_files("tests/renderer/vulkan_frame_lifetime_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer", "cgpui_renderer_vulkan")
        add_packages("vulkansdk")
        add_includedirs(public_includedirs)
        add_syslinks("user32")
        add_tests("default")

    target("vulkan_solid_rect_test")
        set_kind("binary")
        add_files("tests/renderer/vulkan_solid_rect_test.cpp")
        add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer", "cgpui_renderer_vulkan")
        add_packages("vulkansdk")
        add_includedirs(public_includedirs)
        add_syslinks("user32", "gdi32")
        add_tests("default")
end

target("hello_window")
    set_kind("binary")
    add_files("examples/hello_window/main.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer", "cgpui_ui")
    if is_plat("windows") then
        add_deps("cgpui_platform_win32", "cgpui_renderer_vulkan")
        add_tests("windows_first_frame", {runenvs = {CGPUI_EXIT_AFTER_FIRST_FRAME = "1"}})
        add_tests("windows_resize_after_first_frame", {runenvs = {CGPUI_RESIZE_AFTER_FIRST_FRAME = "1"}})
        add_tests("windows_close_after_first_frame", {runenvs = {CGPUI_CLOSE_AFTER_FIRST_FRAME = "1"}})
    elseif is_plat("linux") then
        add_deps("cgpui_platform_linux_wayland", "cgpui_renderer_vulkan")
        add_tests("linux_first_frame", {runenvs = {CGPUI_EXIT_AFTER_FIRST_FRAME = "1"}})
        add_tests("linux_resize_after_first_frame", {runenvs = {CGPUI_RESIZE_AFTER_FIRST_FRAME = "1"}})
        add_tests("linux_close_after_first_frame", {runenvs = {CGPUI_CLOSE_AFTER_FIRST_FRAME = "1"}})
    elseif is_plat("macosx") then
        add_deps("cgpui_platform_macos", "cgpui_renderer_metal")
        add_frameworks("AppKit", "QuartzCore", "Metal")
    else
        add_deps("cgpui_platform_fallback", "cgpui_renderer_fallback")
    end
    add_includedirs(public_includedirs)
