set_project("cgpui")
set_version("0.1.0")
set_languages("c++23")

add_rules("mode.debug", "mode.release")

local public_includedirs = "include"

target("cgpui_core")
    set_kind("static")
    add_files("src/core/*.cpp")
    add_includedirs(public_includedirs, {public = true})

target("cgpui_platform")
    set_kind("static")
    add_files("src/platform/*.cpp")
    remove_files("src/platform/platform_unimplemented.cpp")
    add_deps("cgpui_core")
    add_includedirs(public_includedirs, {public = true})

target("cgpui_platform_fallback")
    set_kind("static")
    add_files("src/platform/platform_unimplemented.cpp")
    add_deps("cgpui_core", "cgpui_platform")
    add_includedirs(public_includedirs, {public = true})

target("cgpui_renderer")
    set_kind("static")
    add_files("src/renderer/*.cpp")
    remove_files("src/renderer/renderer_unimplemented.cpp")
    add_deps("cgpui_core")
    add_includedirs(public_includedirs, {public = true})

target("cgpui_renderer_fallback")
    set_kind("static")
    add_files("src/renderer/renderer_unimplemented.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer")
    add_includedirs(public_includedirs, {public = true})

target("core_header_cleanliness")
    set_kind("binary")
    add_files("tests/header_cleanliness/core_header_cleanliness.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_renderer")
    add_includedirs(public_includedirs)
    add_tests("default")

target("cgpui_ui")
    set_kind("static")
    add_files("src/ui/*.cpp")
    add_deps("cgpui_core", "cgpui_renderer")
    add_includedirs(public_includedirs, {public = true})

target("ui_header_cleanliness")
    set_kind("binary")
    add_files("tests/header_cleanliness/ui_header_cleanliness.cpp")
    add_deps("cgpui_core", "cgpui_renderer", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("render_view_test")
    set_kind("binary")
    add_files("tests/ui/render_view_test.cpp")
    add_deps("cgpui_core", "cgpui_renderer", "cgpui_ui")
    add_includedirs(public_includedirs)
    add_tests("default")

target("hello_window")
    set_kind("binary")
    add_files("examples/hello_window/main.cpp")
    add_deps("cgpui_core", "cgpui_platform", "cgpui_platform_fallback", "cgpui_renderer", "cgpui_renderer_fallback", "cgpui_ui")
    add_includedirs(public_includedirs)
