#pragma once

#include "cgpui/platform/target.hpp"
#include "cgpui/platform/platform_accessibility.hpp"
#include "cgpui/platform/platform_native_menu.hpp"
#include "cgpui/platform/platform_file_dialog.hpp"
#include "cgpui/platform/platform_message_dialog.hpp"
#include "cgpui/platform/platform_open_url.hpp"
#include "cgpui/platform/platform_lifecycle.hpp"
#include "cgpui/platform/platform_window_chrome.hpp"
#include "cgpui/platform/platform_window_close.hpp"
#include "cgpui/platform/platform_window_position.hpp"
#include "cgpui/platform/platform_diagnostics.hpp"
#include "cgpui/platform/platform_window.hpp"
#include "cgpui/platform/platform_application.hpp"
